use wasm_bindgen::prelude::*;

#[wasm_bindgen]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Tile {
  Base = 0,
  BaseNorth = 1,
  BaseEast = 2,
  BaseSouth = 3,
  BaseWest = 4,
  Marsh = 5,
  MarshAlt = 6,
  MarshNorth = 7,
  MarshEast = 8,
  MarshSouth = 9,
  MarshWest = 10,
  MarshNorthEast1 = 11,
  MarshSouthEast1 = 12,
  MarshSouthWest1 = 13,
  MarshNorthWest1 = 14,
  MarshNorthEast3 = 15,
  MarshSouthEast3 = 16,
  MarshSouthWest3 = 17,
  MarshNorthWest3 = 18,
  MarshSaddleNorthEast = 19,
  MarshSaddleSouthEast = 20,
  Rock = 21,
  RockAlt = 22,
  RockNorth = 23,
  RockEast = 24,
  RockSouth = 25,
  RockWest = 26,
  RockNorthEast1 = 27,
  RockSouthEast1 = 28,
  RockSouthWest1 = 29,
  RockNorthWest1 = 30,
  RockNorthEast3 = 31,
  RockSouthEast3 = 32,
  RockSouthWest3 = 33,
  RockNorthWest3 = 34,
  RockSaddleNorthEast = 35,
  RockSaddleSouthEast = 36,
  WaterDeep = 37,
  Water = 38,
  Road1 = 39,
  Road2 = 40,
  RoadNorthEast = 41,
  RoadSouthEast = 42,
  RoadSouthWest = 43,
  RoadNorthWest = 44,
  RoadSlopeNorth = 45,
  RoadSlopeEast = 46,
  RoadSlopeSouth = 47,
  RoadSlopeWest = 48,
  Tree = 49,
  TreeAlt = 50,
  Rocks = 51,
  Reeds = 52,
  GrassPatch = 53,
  Debug = 54,
  Empty = 255,
}
