use wasm_bindgen::prelude::*;

#[wasm_bindgen]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Tile {
  Base = 0,
  BaseNorth = 1,
  BaseEast = 2,
  BaseSouth = 3,
  BaseWest = 4,
  Marsh = 5,
  MarshNorth = 6,
  MarshEast = 7,
  MarshSouth = 8,
  MarshWest = 9,
  MarshNorthEast1 = 10,
  MarshSouthEast1 = 11,
  MarshSouthWest1 = 12,
  MarshNorthWest1 = 13,
  MarshNorthEast3 = 14,
  MarshSouthEast3 = 15,
  MarshSouthWest3 = 16,
  MarshNorthWest3 = 17,
  MarshSaddleNorthEast = 18,
  MarshSaddleSouthEast = 19,
  Rock = 20,
  RockAlt = 21,
  RockNorth = 22,
  RockEast = 23,
  RockSouth = 24,
  RockWest = 25,
  RockNorthEast1 = 26,
  RockSouthEast1 = 27,
  RockSouthWest1 = 28,
  RockNorthWest1 = 29,
  RockNorthEast3 = 30,
  RockSouthEast3 = 31,
  RockSouthWest3 = 32,
  RockNorthWest3 = 33,
  RockSaddleNorthEast = 34,
  RockSaddleSouthEast = 35,
  WaterDeep = 36,
  Water = 37,
  Road1 = 38,
  Road2 = 39,
  RoadNorthEast = 40,
  RoadSouthEast = 41,
  RoadSouthWest = 42,
  RoadNorthWest = 43,
  RoadSlopeNorth = 44,
  RoadSlopeEast = 45,
  RoadSlopeSouth = 46,
  RoadSlopeWest = 47,
  Tree = 48,
  TreeAlt = 49,
  Rocks = 50,
  Reeds = 51,
  GrassPatch = 52,
  Debug = 53,
  Empty = 255,
}
